# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rcpp_removeExps <- function(n, p, q) {
    .Call(`_cyclotomic_Rcpp_removeExps`, n, p, q)
}

